Add a connect closure to websocket
glock45/swifter pull request #319
Opened 2018-06-08 12:37 UTC by marcc-orange

Allows server to start sending events without needing the client
to send some data first.

2018-06-26 01:08 UTC, adamkaplan requested changes
By removing the `_ ` before each argument, you changed this into a breaking change that would need to wait until 2.0...

If you put those `_`s back in there, you would not break everyone's code. API design is a pain...

2018-06-26 11:38 UTC, marcc-orange commented
@adamkaplan Thanks for the feedback.

May I suggest we add a simple wrapper to keep the old API around and maybe mark it deprecated ?

```swift
@available(*, deprecated)
public func websocket(_ text: @escaping (WebSocketSession, String) -> Void,
                      _ binary: @escaping (WebSocketSession, [UInt8]) -> Void,
                      _ pong: @escaping (WebSocketSession, [UInt8]) -> Void) -> ((HttpRequest) -> HttpResponse) {
    return websocket(text: text, binary: binary, pong: pong)
}
```

Another solution is to only add named parameters to the new `connected` and `disconnected` parameters. But this still forces the user to implement all previous closures (like the `pong` closure) even when he is not interested with an empy closure.

In this case the new API  (not introducing any breaking change) would be:

```swift
public func websocket(_ text: @escaping (WebSocketSession, String) -> Void,
                      _ binary: @escaping (WebSocketSession, [UInt8]) -> Void,
                      _ pong: @escaping (WebSocketSession, [UInt8]) -> Void,
                      connected: ((WebSocketSession) -> Void)? = nil,
                      disconnected: ((WebSocketSession) -> Void)? = nil) -> ((HttpRequest) -> HttpResponse) { ... }
```

But I feel the first solution: switching to a new optional closure + named parameters API is a better approach. Introducing the wrapper for the "old" API would prevents breaking anything.

2018-06-26 12:53 UTC, adamkaplan commented
That would properly solve the issue of a major breaking change.

I’m not a project maintainer, let’s see what they say.

2018-06-27 14:50 UTC, adamkaplan approved these changes

2018-07-17 12:23 UTC, marcc-orange commented
Hi @glock45, any thoughts on this PR ? Thanks !

2018-09-24 15:59 UTC, JUSTINMKAUFMAN approved these changes
This is good stuff.

2018-10-23 20:10 UTC, merged